In [1]:
import pandas as pd
import requests as rq

In [2]:
df_pg = pd.read_excel("STG_PGT.xlsx")
df_pg.head(10)

,ID_STG_PGT,VLR_PGT_FAT,DAT_VCT,COD_MDL,QTD_CLI_CAD_POS,QTD_PGT,ID_FNT_ITT,DES_TIP_PSS,DAT_RSS_FNT_ITT,DAT_INC_DBO
0,451,515711,16082022,A04,22,22,67,F,2020-01-16,2020-01-17 17:50:42.746
1,452,60763,26102020,A99,2,2,67,F,2020-01-16,2020-01-17 17:50:42.746
2,453,8588195,24022019,G01,22,22,67,F,2020-01-16,2020-01-17 17:50:42.746
3,454,369084,24062018,B99,16,23,67,F,2020-01-16,2020-01-17 17:50:42.746
4,455,13054,20022021,B99,1,1,67,F,2020-01-16,2020-01-17 17:50:42.746
5,456,1206954,4012018,A04,3,5,67,F,2020-01-16,2020-01-17 17:50:42.746
6,457,21684,24122018,B07,1,1,67,F,2020-01-16,2020-01-17 17:50:42.746
7,458,341157,27032016,B99,10,11,67,F,2020-01-16,2020-01-17 17:50:42.746
8,459,3929,21032018,B05,1,1,67,F,2020-01-16,2020-01-17 17:50:42.746
9,460,12700,28112018,A05,3,3,67,F,2020-01-16,2020-01-17 17:50:42.746

In [3]:
df_pg.dtypes

ID_STG_PGT          int64
VLR_PGT_FAT         int64
DAT_VCT             int64
COD_MDL            object
QTD_CLI_CAD_POS     int64
QTD_PGT             int64
ID_FNT_ITT          int64
DES_TIP_PSS        object
DAT_RSS_FNT_ITT    object
DAT_INC_DBO        object
dtype: object

In [4]:
df_pg['ID_STG_PGT'] = df_pg.ID_STG_PGT.astype('str')
df_pg['ID_FNT_ITT'] = df_pg.ID_FNT_ITT.astype('str')
df_pg.dtypes

ID_STG_PGT         object
VLR_PGT_FAT         int64
DAT_VCT             int64
COD_MDL            object
QTD_CLI_CAD_POS     int64
QTD_PGT             int64
ID_FNT_ITT         object
DES_TIP_PSS        object
DAT_RSS_FNT_ITT    object
DAT_INC_DBO        object
dtype: object

In [5]:
df_pg.head(50)

,ID_STG_PGT,VLR_PGT_FAT,DAT_VCT,COD_MDL,QTD_CLI_CAD_POS,QTD_PGT,ID_FNT_ITT,DES_TIP_PSS,DAT_RSS_FNT_ITT,DAT_INC_DBO
0,451,515711,16082022,A04,22,22,67,F,2020-01-16,2020-01-17 17:50:42.746
1,452,60763,26102020,A99,2,2,67,F,2020-01-16,2020-01-17 17:50:42.746
2,453,8588195,24022019,G01,22,22,67,F,2020-01-16,2020-01-17 17:50:42.746
3,454,369084,24062018,B99,16,23,67,F,2020-01-16,2020-01-17 17:50:42.746
4,455,13054,20022021,B99,1,1,67,F,2020-01-16,2020-01-17 17:50:42.746
5,456,1206954,4012018,A04,3,5,67,F,2020-01-16,2020-01-17 17:50:42.746
6,457,21684,24122018,B07,1,1,67,F,2020-01-16,2020-01-17 17:50:42.746
7,458,341157,27032016,B99,10,11,67,F,2020-01-16,2020-01-17 17:50:42.746
8,459,3929,21032018,B05,1,1,67,F,2020-01-16,2020-01-17 17:50:42.746
9,460,12700,28112018,A05,3,3,67,F,2020-01-16,2020-01-17 17:50:42.746
10,461,85390,13032019,B07,1,1,67,F,2020-01-16,2020-01-17 17:50:42.746
11,462,2024518,19122018,B07,2,2,67,F,2020-01-16,2020-01-17 17:50:42.746
12,463,42250,16062016,B03,1,1,67,F,2020-01-16,2020-01-17 17:50:42.746
13,464,30024,16032018,B03,1,1,67,F,2020-01-16,2020-01-17 17:50:42.746
14,465,153894,9032021,B99,3,3,67,F,2020-01-16,2020-01-17 17:50:42.746
15,466,23651,20042021,A99,1,1,67,F,2020-01-16,2020-01-17 17:50:42.746
16,467,12909,19062018,A99,2,2,67,F,2020-01-16,2020-01-17 17:50:42.746
17,468,116214,5012024,B05,2,2,67,F,2020-01-16,2020-01-17 17:50:42.746
18,469,18595,9052018,B05,1,1,67,F,2020-01-16,2020-01-17 17:50:42.746
19,470,9284,8072020,G01,1,2,67,F,2020-01-16,2020-01-17 17:50:42.746
20,471,61643,21072019,A01,2,2,67,F,2020-01-16,2020-01-17 17:50:42.746
21,472,7546,2112026,A01,1,1,67,F,2020-01-16,2020-01-17 17:50:42.746
22,473,47136,27112018,A01,1,1,67,F,2020-01-16,2020-01-17 17:50:42.746
23,474,934927234,3102019,A04,35932,43662,67,F,2020-01-16,2020-01-17 17:50:42.746
24,475,79063451,1072023,A01,1476,4538,67,F,2020-01-16,2020-01-17 17:50:42.746
25,476,96914588,2022019,A01,1697,1748,67,F,2020-01-16,2020-01-17 17:50:42.746
26,477,292941169,5042023,A01,4139,11621,67,F,2020-01-16,2020-01-17 17:50:42.746
27,478,15560958,15052025,A01,409,792,67,F,2020-01-16,2020-01-17 17:50:42.746
28,479,90739194,2062019,A04,4428,4780,67,F,2020-01-16,2020-01-17 17:50:42.746
29,480,107396454,14122018,A04,2558,2638,67,F,2020-01-16,2020-01-17 17:50:42.746
30,481,69580501,25122018,A04,2644,2818,67,F,2020-01-16,2020-01-17 17:50:42.746
31,482,4997200,17042019,A99,696,728,67,F,2020-01-16,2020-01-17 17:50:42.746
32,483,196551776,1012020,B05,1901,1910,67,F,2020-01-16,2020-01-17 17:50:42.746
33,484,382570748,8112019,B05,3702,3712,67,F,2020-01-16,2020-01-17 17:50:42.746
34,485,292163157,10052019,B99,14041,14660,67,F,2020-01-16,2020-01-17 17:50:42.746
35,486,47474124,26122019,B99,2331,2371,67,F,2020-01-16,2020-01-17 17:50:42.746
36,487,1523017440,6052019,D01,31530,33742,67,F,2020-01-16,2020-01-17 17:50:42.746
37,488,2617324582,18012019,D01,23467,26503,67,F,2020-01-16,2020-01-17 17:50:42.746
38,489,80640110,1052023,A01,1483,4558,67,F,2020-01-16,2020-01-17 17:50:42.746
39,490,22271697,7112016,A01,269,365,67,F,2020-01-16,2020-01-17 17:50:42.746
40,491,3273417,6062019,A99,449,469,67,F,2020-01-16,2020-01-17 17:50:42.746
41,492,2045313,3122018,B99,94,116,67,F,2020-01-16,2020-01-17 17:50:42.746
42,493,2609102,28082018,A01,45,69,67,F,2020-01-16,2020-01-17 17:50:42.746
43,494,8843232,4092019,A01,192,214,67,F,2020-01-16,2020-01-17 17:50:42.746
44,495,3413007,24092018,B05,57,57,67,F,2020-01-16,2020-01-17 17:50:42.746
45,496,21618289,5042017,A01,124,152,67,F,2020-01-16,2020-01-17 17:50:42.746
46,497,444321,31072026,A01,39,41,67,F,2020-01-16,2020-01-17 17:50:42.746
47,498,2067075,4052018,B99,93,160,67,F,2020-01-16,2020-01-17 17:50:42.746
48,499,2606787,4082021,A04,102,104,67,F,2020-01-16,2020-01-17 17:50:42.746
49,500,186211,24112023,A04,20,20,67,F,2020-01-16,2020-01-17 17:50:42.746

In [6]:
df_pg.to_csv('df_pagamentos.csv', index=False, header=True)