# Inicio da analise dos dados disponibilizados pelo SPC Brasil
###  Apenas verificando se está tudo em ordem

In [1]:
#importando pandas e matplotlib
import pandas as pd
%matplotlib inline

In [20]:
#criando dataframe e abrindo o arquivo excel
#Extração das Informações da tabela “modalidade_cad_positivo”.
#Cadastro de todas as modalidades que foram captadas informações para o cadastro positivo.
#Campos disponíveis no arquivo: ID_STG_MDL, COD_MDL, DES_MDL e DAT_INC_DBO.

df_mdl = pd.read_excel('STG_MDL.xlsx')

In [21]:
df_mdl.head(20)

,ID_STG_MDL,COD_MDL,DES_MDL,DAT_INC_DBO
0,17,E02,ADIANTAMENTO DEPOSITANTE,2019-12-19 13:37:34.759
1,13,B99,OUTROS FINANCIAMENTOS,2019-12-19 13:37:34.759
2,15,D01,CARTAO DE CREDITO,2019-12-19 13:37:34.759
3,19,G01,TITULOS DESCONTADOS,2019-12-19 13:37:34.759
4,2,A02,EMPRESTIMO - CAPITAL DE GIRO,2019-12-19 13:37:34.759
5,3,A04,EMPRESTIMO - CREDITO PESSOAL,2019-12-19 13:37:34.759
6,16,E01,CHEQUE ESPECIAL E CONTA GARANTIDA,2019-12-19 13:37:34.759
7,8,B03,FINANCIAMENTO - IMOBILIARIOS SFH,2019-12-19 13:37:34.759
8,7,B02,FINANCIAMENTO - IMPORTACAO E EXPORTACAO,2019-12-19 13:37:34.759
9,4,A05,EMPRESTIMO - MICROCREDITO,2019-12-19 13:37:34.759
10,9,B04,FINANCIAMENTO - MICROCREDITO,2019-12-19 13:37:34.759
11,12,B07,FINANCIAMENTO - ARREENDAMENTO,2019-12-19 13:37:34.759
12,18,F01,AVAIS E FIANCASA HONRADOS,2019-12-19 13:37:34.759
13,11,B06,FINANCIAMENTO - IMOBILIARIO (OUTROS),2019-12-19 13:37:34.759
14,14,C01,CONSORCIO,2019-12-19 13:37:34.759
15,1,A01,EMPRESTIMO - CONSIGNADO,2019-12-19 13:37:34.759
16,10,B05,FINANCIAMENTO - AQUISICAO DE BENS (VEICULOS),2019-12-19 13:37:34.759
17,5,A99,OUTROS EMPRESTIMOS,2019-12-19 13:37:34.759
18,6,B01,FINANCIAMENTO - RURAL E AGROINDUSTRIAL,2019-12-19 13:37:34.759

In [22]:
df_mdl.dtypes

ID_STG_MDL      int64
COD_MDL        object
DES_MDL        object
DAT_INC_DBO    object
dtype: object

In [45]:
#abrindo a tabela de movimentação
#Extração das Informações da tabela “mvt_cad_pos”.
#Registro de todas as atividades relacionadas as movimentações de credito do cad pos.
#Campos disponíveis no arquivo: ID_STG_MVT_CRD, VLR_SDO_UTZ_CRD_RTO, VLR_TOT_FAT, VLR_MIM_FAT,
#VLR_PCL_FAT, QTD_CLI_CAD_POS, QTD_MVT, DES_TIP_PSS, ID_FNT_ITT, COD_MDL, DAT_RSS_FNT_ITT e DAT_INC_DBO.

df_mvt = pd.read_excel('STG_MVT_CRD.xlsx', usecols=[0, 5, 6, 7, 8, 9, 10, 11, 12])
df_mvt.head(20)

#p.s ocultei algumas colunas para facilitar a leitura

,ID_STG_MVT_CRD,QTD_CLI_CAD_POS,QTD_MVT,DES_TIP_PSS,ID_FNT_ITT,COD_MDL,DAT_RSS_FNT_ITT,DAT_INC_DBO
0,1,37186,677272,F,67,C01,2020-01-16,2020-01-17 17:49:17.524
1,2,307070,2741111,F,67,B99,2020-01-16,2020-01-17 17:49:17.524
2,3,601,1964,F,67,B01,2020-01-16,2020-01-17 17:49:17.524
3,4,18820,244041,F,67,B03,2020-01-16,2020-01-17 17:49:17.524
4,5,2,4,F,67,F01,2020-01-16,2020-01-17 17:49:17.524
5,6,33,329,F,67,B07,2020-01-16,2020-01-17 17:49:17.524
6,7,721836,10020532,F,67,A04,2020-01-16,2020-01-17 17:49:17.524
7,8,135773,1797516,F,67,B05,2020-01-16,2020-01-17 17:49:17.524
8,9,5061,38003,F,67,A05,2020-01-16,2020-01-17 17:49:17.524
9,10,194378,194921,F,67,E01,2020-01-16,2020-01-17 17:49:17.524
10,11,1890,123559,F,67,G01,2020-01-16,2020-01-17 17:49:17.524
11,12,494442,19241809,F,67,A01,2020-01-16,2020-01-17 17:49:17.524
12,13,46495,230867,F,67,A99,2020-01-16,2020-01-17 17:49:17.524
13,14,43,330,F,67,B06,2020-01-16,2020-01-17 17:49:17.524
14,15,1840240,21748501,F,67,D01,2020-01-16,2020-01-17 17:49:17.524

In [46]:
df_mvt.dtypes

ID_STG_MVT_CRD      int64
QTD_CLI_CAD_POS     int64
QTD_MVT             int64
DES_TIP_PSS        object
ID_FNT_ITT          int64
COD_MDL            object
DAT_RSS_FNT_ITT    object
DAT_INC_DBO        object
dtype: object

In [47]:
df_mvt['COD_MDL'].value_counts()

G01    1
A99    1
B01    1
C01    1
A05    1
F01    1
A01    1
A04    1
B06    1
B03    1
E01    1
D01    1
B05    1
B07    1
B99    1
Name: COD_MDL, dtype: int64

In [49]:
#quantidade de clientes com cadastro positivo
df_mvt.nlargest(15, 'QTD_CLI_CAD_POS')

,ID_STG_MVT_CRD,QTD_CLI_CAD_POS,QTD_MVT,DES_TIP_PSS,ID_FNT_ITT,COD_MDL,DAT_RSS_FNT_ITT,DAT_INC_DBO
14,15,1840240,21748501,F,67,D01,2020-01-16,2020-01-17 17:49:17.524
6,7,721836,10020532,F,67,A04,2020-01-16,2020-01-17 17:49:17.524
11,12,494442,19241809,F,67,A01,2020-01-16,2020-01-17 17:49:17.524
1,2,307070,2741111,F,67,B99,2020-01-16,2020-01-17 17:49:17.524
9,10,194378,194921,F,67,E01,2020-01-16,2020-01-17 17:49:17.524
7,8,135773,1797516,F,67,B05,2020-01-16,2020-01-17 17:49:17.524
12,13,46495,230867,F,67,A99,2020-01-16,2020-01-17 17:49:17.524
0,1,37186,677272,F,67,C01,2020-01-16,2020-01-17 17:49:17.524
3,4,18820,244041,F,67,B03,2020-01-16,2020-01-17 17:49:17.524
8,9,5061,38003,F,67,A05,2020-01-16,2020-01-17 17:49:17.524
10,11,1890,123559,F,67,G01,2020-01-16,2020-01-17 17:49:17.524
2,3,601,1964,F,67,B01,2020-01-16,2020-01-17 17:49:17.524
13,14,43,330,F,67,B06,2020-01-16,2020-01-17 17:49:17.524
5,6,33,329,F,67,B07,2020-01-16,2020-01-17 17:49:17.524
4,5,2,4,F,67,F01,2020-01-16,2020-01-17 17:49:17.524

In [61]:
#a modalidade de cartão de credito tem o maior numero de ovimentações, então também é natural que tenha mais clientes
# com cadastro positivo